/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/layout/default-layout.vue')['default']
    DialogBox: typeof import('./src/components/DialogBox/DialogBox.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox/MessageBox.vue')['default']
    NotFound: typeof import('./src/components/not-found.vue')['default']
    QuestionBox: typeof import('./src/components/QuestionBox/QuestionBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAffix: typeof import('tdesign-vue-next')['Affix']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCollapse: typeof import('tdesign-vue-next')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next')['CollapsePanel']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TestContent: typeof import('./src/components/DialogBox/TestContent.vue')['default']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    TInput: typeof import('tdesign-vue-next')['Input']
    TOption: typeof import('tdesign-vue-next')['Option']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TStickyItem: typeof import('tdesign-vue-next')['StickyItem']
    TStickyTool: typeof import('tdesign-vue-next')['StickyTool']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
