/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/components/layout/default-layout.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox/MessageBox.vue')['default']
    NotFound: typeof import('./src/components/not-found.vue')['default']
    QuestionBox: typeof import('./src/components/QuestionBox/QuestionBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TStickyItem: typeof import('tdesign-vue-next')['StickyItem']
    TStickyTool: typeof import('tdesign-vue-next')['StickyTool']
  }
}
